=== NadzeyaParkhimovich/TATJAVA01_2017_Task05_Andrei_Lisitski/Menu.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.epam.task5.org"
	xmlns:tns="http://www.epam.task5.org" 
	elementFormDefault="unqualified">

	<element name="menu">
		<complexType>
			<sequence>
				<element name="dish" type="tns:food-type" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<simpleType name="category">
		<restriction base="string">
			<enumeration value="Холодные закуски" />
			<enumeration value="Горячие закуски" />
			<enumeration value="Завтрак" />
		</restriction>
	</simpleType>

	<simpleType name="weight-type">
		<restriction base="positiveInteger">
			<minInclusive value="1" />
			<pattern value="[0-9]" />
		</restriction>
	</simpleType>

	<simpleType name="price-type">
		<restriction base="positiveInteger">
			<minInclusive value="1" />
			<pattern value="[0-9]" />
		</restriction>
	</simpleType>

	<complexType name="food-type">
		<sequence>
			<element name="meal" type="tns:category" />
			<element name="name" type="string" />
			<element name="consist" type="string" />
			<element name="weight" type="tns:weight-type" />
			<element name="price" type="tns:price-type" />
		</sequence>
		<attribute name="id" type="integer" />
	</complexType>

</schema>

=== NadzeyaParkhimovich/TATJAVA01_2017_Task05_Andrei_Lisitski/RestaurantMenu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menu xmlns="http://www.epam.task5.org/Menu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.epam.task5.org/Menu Menu.xsd">

	<dish id="1">
		<category>Холодные закуски</category>
		<name>Ассорти рыбное</name>
		<consist>Слабосоленая форель, семга</consist>
		<weight>5</weight>
		<price>6</price>
	</dish>

	<dish id="2">
		<category>Холодные закуски</category>
		<name>Тарталетки с красной икрой</name>
		<consist>Тарталетки с красной икрой</consist>
		<weight>2</weight>
		<price>1</price>
	</dish>

</menu>
